version: "3.7"

services:
  web:
    image: nginx:latest
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - app
    #  - db
    environment:
      DOMAIN: dev00.blog.dshimizu.jp
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ./docker/nginx/log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./wordpress:/var/www/html/wordpress
      #- type: bind
      #  source: ./wordpress
      #  target: /var/www/html/wordpress
  app:
    build: 
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: php:fpm
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html/wordpress:rw
      #- type: bind
      #  source: ./wordpress
      #  target: /var/www/html/wordpress
        #volume:
        #  nocopy: true
  db:
    build:
      context: ./docker
      dockerfile: ./mysql/Dockerfile
    image: mysql:latest
    env_file: .env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/mysql:/var/lib/mysql
      - ./docker/mysql/custom_mysqld.cnf:/etc/mysql/conf.d/custom_mysqld.cnf
#volumes:
#  wordpress:
#    external: true
#volumes:
#  app_root:
#    driver: local
#    driver_opts:
#      type: none
#      device: ./wordpress
#      o: bind
