version: "2"
services:
  web:
    image: nginx:latest
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - db
    environment:
      DOMAIN: dev04.blog.dshimizu.jp
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/wordpress.conf:/etc/nginx/conf.d/wordpress.conf:ro
      - ./web/log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    volumes_from:
      - app
  app:
    build: ./app
    image: php:fpm
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html/wordpress:rw
      #- ./app/etc:/usr/local/etc
  db:
    build: ./db
    image: mysql:latest
    env_file: .env
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/custom_mysqld.cnf:/etc/mysql/conf.d/custom_mysqld.cnf
